import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Hack Nerd Font"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.9
decorations = "full"

[window.padding]
x = 5
y = 5
